## base
APPLICATION_NAME=xxx

## apollo
apollo_meta=http://apollo-metaserver-qa.s.qima-inc.com/

## DB
DB_Service_db_sales_ai_host=rds-single4-1.qa.s.qima-inc.com
DB_Service_db_sales_ai_port=3310
DB_Service_db_sales_ai_user=u2_ai_sales
DB_Service_db_sales_ai_dbname=ai_sales_service
DB_Service_db_sales_ai_password=Ph2SZYLZP0j2xDA6LL5z

## proxy
proxy_url=http://proxy-static-qa.s.qima-inc.com